# Generated by Django 3.1.5 on 2021-02-05 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_install_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='edited',
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, default='', help_text='The content of the feedback response. You may treat this as plain text for the purposes of this project. This plain text may contain newlines and tabs, both of which should be rendered.')),
                ('editor', models.ForeignKey(help_text='The editor who is providing the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
                ('feedback_request', models.ForeignKey(help_text='The FeedbackRequest the FeedbackResponse is for.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='project.feedbackrequest')),
            ],
        ),
    ]
